---
apiVersion: v1
kind: Secret
metadata:
  name: rjac432-rjac432-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/rjac432-gateway-gitops
